### ISSUE TITLE
关于retrain的问题

### ISSUE THREAD

**Issue by sweartoyou** [imcsq/ASE21-QAAskeR#1]
当我在使用replication中提供的方法训练模型时，总会有一些报错
直接使用时会报这样的错误
![41f8dc0b4860f9666dc067f70825ece](https://user-images.githubusercontent.com/43296821/148897284-c1c5c309-e817-4974-b7d1-9bf206cdc495.png)
当我对run.py中140行代码进行修改成为model.module时又会有这样的报错
![e95e10527e2044de17b6d2b263c1f14](https://user-images.githubusercontent.com/43296821/148897420-d46f7c5a-03f5-4e8f-8dc9-9b440da3df46.png)
如果把t5.py里的decoder_past_key_value_stares一行注释掉会出现更多奇怪的错误
（我的环境配置除了spacy外其他均与提供的配置一样）请问我的问题是出在哪里呢

**Comment by imcsq** [comment]
您好，这个错误应该是调用被测模型的时候出来的问题，是pytorch和transformers库之间的调用碰出来的，他俩之间接口没匹配上。感谢您的反馈，不过目前我们可能没法短时间回复这个crash在第三方库之间的bug，我们做实验的时候正常，我们有空安排看看在全新环境上也再按我们replicationpackage部署一遍找找问题，如果有发现类似的情况 & 有解决方案，来回复您。感谢反馈~

**Comment by imcsq** [comment]
对了，模型训练是requirements4replication.txt在这套环境里，和工具测试用的requirements4tool.txt不一样，您看看是对的吗？我们回头安排再重新部署检查一轮，如果发现相应错误 来回复&更新相关说明。

**Comment by sweartoyou** [comment]
感谢您如此迅速的回复，我在训练模型时环境确实是用成了tool的环境，但当我把环境重新配置后重新运行代码后仍然遇到了上面提到的相同的问题，尝试了transformers的各个版本后也是一样，我不知道我的问题出现在哪里，希望您能给我一些指导，不胜感激

**Comment by imcsq** [comment]
> 感谢您如此迅速的回复，我在训练模型时环境确实是用成了tool的环境，但当我把环境重新配置后重新运行代码后仍然遇到了上面提到的相同的问题，尝试了transformers的各个版本后也是一样，我不知道我的问题出现在哪里，希望您能给我一些指导，不胜感激

您好，我们刚安排了同学重新在全新的机器上建立新环境，按照脚本在全新的环境里重新安装所需包之后运行代码，是可以正常训练没有遇到问题的。
您可以试试这两个方案的任意一个，我们验证过都是可行的：
1. 用conda建立一个**全新**的环境（python 3.8），然后直接用pip install -r requirements4replication.txt基于我们提供的依赖文件恢复完整环境，再次尝试训练。
2. 用conda建立一个**全新**的环境（python 3.8）后，执行：
```bash
pip install transformers==3.2.0
pip install torch==1.10.1+cu113 torchvision==0.11.2+cu113 torchaudio==0.10.1+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html
pip install tqdm
```

训练准备被测模型主要是基于UnifiedQA官方说明和依赖开源transformers库的代码完成复现的，依赖transformers库的一些版本更新接口变化较大 本身和pytorch等组件的匹配要求比较严格，环境小差异可能会造成他们的库之间对不上的问题，从而导致他们的库之间不能正确调用。
我们尝试了按照我们的教程使用 或者 按照上述第二种方法，都是可以正常恢复环境并进行训练的。您可以准备个全新的也再按顺序尝试一下看看，避免三方库内部的一些小问题导致无法复现的哈。

**Comment by sweartoyou** [comment]
> 

感谢您的回复。但我在按照您给出的方案进行实验时出现了这样的问题：
当我安装的版本是torch==1.10.1+cu113 torchvision==0.11.2+cu113 torchaudio==0.10.1+cu113时我将无法使用gpu，我在查询了一番后尝试对cuda的版本进行修改但仍然无法解决，而当我安装的版本是torch==1.10.1（torch version:1.10.1 + cu102）时可以使用gpu但会报和之前类似的错误
（我的配置是 CUDA vision:10.2 Driver vision: 430.14 ）
您对我遇到的状况是否有想法？
非常感谢

**Comment by imcsq** [comment]
> > 
> 
> 感谢您的回复。但我在按照您给出的方案进行实验时出现了这样的问题： 当我安装的版本是torch==1.10.1+cu113 torchvision==0.11.2+cu113 torchaudio==0.10.1+cu113时我将无法使用gpu，我在查询了一番后尝试对cuda的版本进行修改但仍然无法解决，而当我安装的版本是torch==1.10.1（torch version:1.10.1 + cu102）时可以使用gpu但会报和之前类似的错误 （我的配置是 CUDA vision:10.2 Driver vision: 430.14 ） 您对我遇到的状况是否有想法？ 非常感谢

我们下午尝试复现过，似乎没有发现问题。我们是在ubuntu20.04+miniconda的环境下安装的。
记得一定开一个 **全新、独立** 的conda环境，避免和已有的依赖包影响。
430.14应该不是3系的新显卡对吧？可以考虑用conda装cudatoolkit10.2和pytorch1.7.1，conda的安装可能比pip稳定一些。在独立的新环境里准备pytorch1.7.1（或1.10.1）和transformers==3.2.0之后，应该是可以正常使用的，不需要对我们的代码做任何修改的。
关于unifiedQA被测模型的训练这块，也可以参考unifiedQA的官方说明（https://github.com/allenai/unifiedqa）再看看。

**Comment by sweartoyou** [comment]
> > > 
> > 
> > 
> > 感谢您的回复。但我在按照您给出的方案进行实验时出现了这样的问题： 当我安装的版本是torch==1.10.1+cu113 torchvision==0.11.2+cu113 torchaudio==0.10.1+cu113时我将无法使用gpu，我在查询了一番后尝试对cuda的版本进行修改但仍然无法解决，而当我安装的版本是torch==1.10.1（torch version:1.10.1 + cu102）时可以使用gpu但会报和之前类似的错误 （我的配置是 CUDA vision:10.2 Driver vision: 430.14 ） 您对我遇到的状况是否有想法？ 非常感谢
> 
> 我们下午尝试复现过，似乎没有发现问题。我们是在ubuntu20.04+miniconda的环境下安装的。 记得一定开一个 **全新、独立** 的conda环境，避免和已有的依赖包影响。 430.14应该不是3系的新显卡对吧？可以考虑用conda装cudatoolkit10.2和pytorch1.7.1，conda的安装可能比pip稳定一些。在独立的新环境里准备pytorch1.7.1（或1.10.1）和transformers==3.2.0之后，应该是可以正常使用的，不需要对我们的代码做任何修改的。 关于unifiedQA被测模型的训练这块，也可以参考unifiedQA的官方说明（ https://github.com/allenai/unifiedqa ）再看看。

我在更换了服务器之后，按照您给出的方案cuda是可用的，但我在训练模型时仍然会出现我在第一条问题列出的错误，但这次不一样的是，在这一步
![1b00269347d93eb57aeaedd91618310](https://user-images.githubusercontent.com/43296821/149663229-9ac3b94d-eaa0-4a8b-aaa7-c83590255e55.png)
它会训练到5之后立刻停止并报出如下错误
![1642341774(1)](https://user-images.githubusercontent.com/43296821/149663255-d153aa58-4f4d-4a6a-84ae-20723cb43159.png)
![1642341781(1)](https://user-images.githubusercontent.com/43296821/149663259-d97fa868-1e70-429e-958f-1b3846f2e408.png)
您是否遇到过类似的情况？有没有解决的办法？
（我的环境是：GeForce RTX 3090 CUDA Version：11.1 Diver Version：455.45.01 
torch==1.7.1+cu110(已经尝试过您给出的方案torch==1.10.1+cu113但无法训练模型)
ubuntu16.04+miniconda）

**Comment by imcsq** [comment]
> > > > 
> > > 
> > > 
> > > 感谢您的回复。但我在按照您给出的方案进行实验时出现了这样的问题： 当我安装的版本是torch==1.10.1+cu113 torchvision==0.11.2+cu113 torchaudio==0.10.1+cu113时我将无法使用gpu，我在查询了一番后尝试对cuda的版本进行修改但仍然无法解决，而当我安装的版本是torch==1.10.1（torch version:1.10.1 + cu102）时可以使用gpu但会报和之前类似的错误 （我的配置是 CUDA vision:10.2 Driver vision: 430.14 ） 您对我遇到的状况是否有想法？ 非常感谢
> > 
> > 
> > 我们下午尝试复现过，似乎没有发现问题。我们是在ubuntu20.04+miniconda的环境下安装的。 记得一定开一个 **全新、独立** 的conda环境，避免和已有的依赖包影响。 430.14应该不是3系的新显卡对吧？可以考虑用conda装cudatoolkit10.2和pytorch1.7.1，conda的安装可能比pip稳定一些。在独立的新环境里准备pytorch1.7.1（或1.10.1）和transformers==3.2.0之后，应该是可以正常使用的，不需要对我们的代码做任何修改的。 关于unifiedQA被测模型的训练这块，也可以参考unifiedQA的官方说明（ https://github.com/allenai/unifiedqa ）再看看。
> 
> 我在更换了服务器之后，按照您给出的方案cuda是可用的，但我在训练模型时仍然会出现我在第一条问题列出的错误，但这次不一样的是，在这一步 ![1b00269347d93eb57aeaedd91618310](https://user-images.githubusercontent.com/43296821/149663229-9ac3b94d-eaa0-4a8b-aaa7-c83590255e55.png) 它会训练到5之后立刻停止并报出如下错误 ![1642341774(1)](https://user-images.githubusercontent.com/43296821/149663255-d153aa58-4f4d-4a6a-84ae-20723cb43159.png) ![1642341781(1)](https://user-images.githubusercontent.com/43296821/149663259-d97fa868-1e70-429e-958f-1b3846f2e408.png) 您是否遇到过类似的情况？有没有解决的办法？ （我的环境是：GeForce RTX 3090 CUDA Version：11.1 Diver Version：455.45.01 torch==1.7.1+cu110(已经尝试过您给出的方案torch==1.10.1+cu113但无法训练模型) ubuntu16.04+miniconda）

显存满了哦。
首先现在能训练到5，说明之前的库匹配问题已经解决，已经能够正常训练了。
目前报错的是显存不足了哦，看报错信息，24G的总显存，似乎已分配了16.04G显存，但只有21.56M空余？您是否同时运行了其他进程占用了显存？UnifiedQA模型较大，几乎需要消耗整个3090的显存的哈，关闭其他占用显存的程序看看。

**Comment by sweartoyou** [comment]
> > > > > 
> > > > 
> > > > 
> > > > 感谢您的回复。但我在按照您给出的方案进行实验时出现了这样的问题： 当我安装的版本是torch==1.10.1+cu113 torchvision==0.11.2+cu113 torchaudio==0.10.1+cu113时我将无法使用gpu，我在查询了一番后尝试对cuda的版本进行修改但仍然无法解决，而当我安装的版本是torch==1.10.1（torch version:1.10.1 + cu102）时可以使用gpu但会报和之前类似的错误 （我的配置是 CUDA vision:10.2 Driver vision: 430.14 ） 您对我遇到的状况是否有想法？ 非常感谢
> > > 
> > > 
> > > 我们下午尝试复现过，似乎没有发现问题。我们是在ubuntu20.04+miniconda的环境下安装的。 记得一定开一个 **全新、独立** 的conda环境，避免和已有的依赖包影响。 430.14应该不是3系的新显卡对吧？可以考虑用conda装cudatoolkit10.2和pytorch1.7.1，conda的安装可能比pip稳定一些。在独立的新环境里准备pytorch1.7.1（或1.10.1）和transformers==3.2.0之后，应该是可以正常使用的，不需要对我们的代码做任何修改的。 关于unifiedQA被测模型的训练这块，也可以参考unifiedQA的官方说明（ https://github.com/allenai/unifiedqa ）再看看。
> > 
> > 
> > 我在更换了服务器之后，按照您给出的方案cuda是可用的，但我在训练模型时仍然会出现我在第一条问题列出的错误，但这次不一样的是，在这一步 ![1b00269347d93eb57aeaedd91618310](https://user-images.githubusercontent.com/43296821/149663229-9ac3b94d-eaa0-4a8b-aaa7-c83590255e55.png) 它会训练到5之后立刻停止并报出如下错误 ![1642341774(1)](https://user-images.githubusercontent.com/43296821/149663255-d153aa58-4f4d-4a6a-84ae-20723cb43159.png) ![1642341781(1)](https://user-images.githubusercontent.com/43296821/149663259-d97fa868-1e70-429e-958f-1b3846f2e408.png) 您是否遇到过类似的情况？有没有解决的办法？ （我的环境是：GeForce RTX 3090 CUDA Version：11.1 Diver Version：455.45.01 torch==1.7.1+cu110(已经尝试过您给出的方案torch==1.10.1+cu113但无法训练模型) ubuntu16.04+miniconda）
> 
> 显存满了哦。 首先现在能训练到5，说明之前的库匹配问题已经解决，已经能够正常训练了。 目前报错的是显存不足了哦，看报错信息，24G的总显存，似乎已分配了16.04G显存，但只有21.56M空余？您是否同时运行了其他进程占用了显存？Large size的UnifiedQA模型较大，几乎需要消耗整个3090的显存的哈，关闭其他占用显存的程序看看。 也可以考虑减小batch size。

感谢您的帮助！！已经可以开始训练了
此外我还想请问您的hybrid trainning set是对三个数据集的直接拼接还是随机组合呢？
我在拜读了您的论文后没有发现这点
感激不尽

**Comment by imcsq** [comment]
> > > > > > 
> > > > > 
> > > > > 
> > > > > 感谢您的回复。但我在按照您给出的方案进行实验时出现了这样的问题： 当我安装的版本是torch==1.10.1+cu113 torchvision==0.11.2+cu113 torchaudio==0.10.1+cu113时我将无法使用gpu，我在查询了一番后尝试对cuda的版本进行修改但仍然无法解决，而当我安装的版本是torch==1.10.1（torch version:1.10.1 + cu102）时可以使用gpu但会报和之前类似的错误 （我的配置是 CUDA vision:10.2 Driver vision: 430.14 ） 您对我遇到的状况是否有想法？ 非常感谢
> > > > 
> > > > 
> > > > 我们下午尝试复现过，似乎没有发现问题。我们是在ubuntu20.04+miniconda的环境下安装的。 记得一定开一个 **全新、独立** 的conda环境，避免和已有的依赖包影响。 430.14应该不是3系的新显卡对吧？可以考虑用conda装cudatoolkit10.2和pytorch1.7.1，conda的安装可能比pip稳定一些。在独立的新环境里准备pytorch1.7.1（或1.10.1）和transformers==3.2.0之后，应该是可以正常使用的，不需要对我们的代码做任何修改的。 关于unifiedQA被测模型的训练这块，也可以参考unifiedQA的官方说明（ https://github.com/allenai/unifiedqa ）再看看。
> > > 
> > > 
> > > 我在更换了服务器之后，按照您给出的方案cuda是可用的，但我在训练模型时仍然会出现我在第一条问题列出的错误，但这次不一样的是，在这一步 ![1b00269347d93eb57aeaedd91618310](https://user-images.githubusercontent.com/43296821/149663229-9ac3b94d-eaa0-4a8b-aaa7-c83590255e55.png) 它会训练到5之后立刻停止并报出如下错误 ![1642341774(1)](https://user-images.githubusercontent.com/43296821/149663255-d153aa58-4f4d-4a6a-84ae-20723cb43159.png) ![1642341781(1)](https://user-images.githubusercontent.com/43296821/149663259-d97fa868-1e70-429e-958f-1b3846f2e408.png) 您是否遇到过类似的情况？有没有解决的办法？ （我的环境是：GeForce RTX 3090 CUDA Version：11.1 Diver Version：455.45.01 torch==1.7.1+cu110(已经尝试过您给出的方案torch==1.10.1+cu113但无法训练模型) ubuntu16.04+miniconda）
> > 
> > 
> > 显存满了哦。 首先现在能训练到5，说明之前的库匹配问题已经解决，已经能够正常训练了。 目前报错的是显存不足了哦，看报错信息，24G的总显存，似乎已分配了16.04G显存，但只有21.56M空余？您是否同时运行了其他进程占用了显存？Large size的UnifiedQA模型较大，几乎需要消耗整个3090的显存的哈，关闭其他占用显存的程序看看。 也可以考虑减小batch size。
> 
> 感谢您的帮助！！已经可以开始训练了 此外我还想请问您的hybrid trainning set是对三个数据集的直接拼接还是随机组合呢？ 我在拜读了您的论文后没有发现这点 感激不尽

好的。恭喜顺利完成。数据是混合的，不过这里主要是在准备被测模型，任何能达到预期性能的训练方式都是可以接受的。
