### ISSUE TITLE
关于MR1生成数据的问题

### ISSUE THREAD

**Issue by cicilzx** [imcsq/ASE21-QAAskeR#2]
你好！我想问一下MR1生成问题，运行unilm-v1时的模型路径model_recover_path，是需要提供哪个模型呢？我用了unilm的GitHub仓库里提供的ggw10k_model，但是生成出来的句子并不易于理解，是否是因为我用的模型不对呢？

生成出来的句子类似于：
IPCC Trust Fund provides funds to fight climate change
unep wmo start fund for global warming
wmo funds secretary
unep funds deputy secretary
unep funds deputy secretary
IPCC has to follow financial regulations

**Comment by imcsq** [comment]
你好，感谢关注。是需要使用用于生成问题的UniLM模型。在这儿可以下载到：
![2HY%V76GEPC~5MI}{44G7Z2](https://user-images.githubusercontent.com/7814845/164219334-10a1b435-23f2-45c6-b748-1661b447895a.png)
网址是https://drive.google.com/file/d/1JN2wnkSRotwUnJ_Z-AbWwoPdP53Gcfsn/view。

**Comment by imcsq** [comment]
你好，感谢关注。是需要使用用于生成问题的UniLM模型。在这儿可以下载到：
![OYVNR7GE_AS0 5)`4_73MBJ](https://user-images.githubusercontent.com/7814845/164219711-5c0bd9ce-5345-403b-a2e0-e7c84313f913.png)

网址是https://drive.google.com/file/d/1JN2wnkSRotwUnJ_Z-AbWwoPdP53Gcfsn/view。
（如果Issue回复不及时，也可以直接邮箱联系~

**Comment by cicilzx** [comment]
感谢回复，已解决！祝科研顺利~！

**Comment by cicilzx** [comment]
> 你好，感谢关注。是需要使用用于生成问题的UniLM模型。在这儿可以下载到： ![OYVNR7GE_AS0 5)`4_73MBJ](https://user-images.githubusercontent.com/7814845/164219711-5c0bd9ce-5345-403b-a2e0-e7c84313f913.png)
> 
> 网址是https://drive.google.com/file/d/1JN2wnkSRotwUnJ_Z-AbWwoPdP53Gcfsn/view （如果Issue回复不及时，也可以直接邮箱联系~

感谢回复，已解决！祝科研顺利~！
